### ISSUE TITLE
tslint 5.5 + tslint-react 3.0 - Cannot find module 'tsutils' due to jsxAligmentRule

### ISSUE THREAD

**Issue by xaviergonz** [palantir/tslint-react#109]
When I use tslint 5.5 + tslint-react 3.0 + ts 2.4.1 webstorm complains about the following:

```
Error: Cannot find module 'tsutils'

Error: Cannot find module 'tsutils'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\VSProjects\skirmish-vt-gitlab\skirmish-vt-4\node_modules\tslint-react\rules\jsxAlignmentRule.js:30:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

it seems to complain about the lack of the tsutils require inside that jsxAligmentRule.js file

**Comment by xaviergonz** [comment]
nevermind, I just noticed tsutils is a peer dependency that I didn't install
