### ISSUE TITLE
Could not find custom rule directory: codelyzer

### ISSUE THREAD

**Issue by tlaak** [palantir/tslint-react#177]
I'm getting this error in vscode-tslint output about a missing codelyzer custom rule directory. This is a React project so there shouldn't be any need for codelyzer. The filename after `while validating:` varies a bit, it's usually the one I have active in VS Code.

```bash
[Info  - 15:52:24] vscode-tslint: 'Could not find custom rule directory: /Users/me/myproject/node_modules/codelyzer' while validating: /Users/me/myproject/src/sagas/mySaga.ts stacktrace: FatalError: Could not find custom rule directory: /Users/me/myproject/node_modules/codelyzer
    at new FatalError (/Users/me/myproject/node_modules/tslint/lib/error.js:27:28)
    at loadCachedRule (/Users/me/myproject/node_modules/tslint/lib/ruleLoader.js:116:19)
    at /Users/me/myproject/node_modules/tslint/lib/ruleLoader.js:77:82
    at Object.find (/Users/me/myproject/node_modules/tslint/lib/utils.js:139:22)
    at findRule (/Users/me/myproject/node_modules/tslint/lib/ruleLoader.js:77:17)
    at Object.loadRules (/Users/me/myproject/node_modules/tslint/lib/ruleLoader.js:38:20)
    at Linter.getEnabledRules (/Users/me/myproject/node_modules/tslint/lib/linter.js:311:25)
    at Linter.lint (/Users/me/myproject/node_modules/tslint/lib/linter.js:127:29)
    at /Users/me/.vscode/extensions/eg2.tslint-1.0.34/server/tslintServer.js:451:24
    at Generator.next (<anonymous>)
```

My tslint.json
```json
{
  "extends": ["tslint:recommended", "tslint-react", "tslint-config-prettier"],
  "linterOptions": {
    "exclude": ["build", "coverage", "node_modules"]
  },
  "rules": {
    "ordered-imports": false,
    "object-literal-sort-keys": false,
    "member-ordering": false,
    "no-console": false
  }
}
```

The error goes away if I remove `tslint-react` from the extends array.

When I add a `console.log(configuration)` on line 126 in `tslint/lib/linter.js` the above error message comes right after `'no-bitwise' => { ruleArguments: [], ruleSeverity:`

**Comment by adidahiya** [comment]
Closing due to age, please reopen if this is still an issue with the latest tslint. Ideally provide a minimal repro we can debug
