### ISSUE TITLE
jsxWrapMultilineRule: TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by Strate** [palantir/tslint-react#86]
tslint-react@2.5.0

Happens with phpStorm tslint integration

```
TypeError: Cannot read property 'some' of undefined
    at Object.doesIntersect (/devel/src/hotfix/megaplan/front/node_modules/tslint/lib/language/utils.js:27:29)
    at _loop_1 (/devel/src/hotfix/megaplan/front/node_modules/tslint/lib/language/rule/abstractRule.js:47:26)
    at Rule.AbstractRule.filterFailures (/devel/src/hotfix/megaplan/front/node_modules/tslint/lib/language/rule/abstractRule.js:54:13)
    at Rule.AbstractRule.applyWithWalker (/devel/src/hotfix/megaplan/front/node_modules/tslint/lib/language/rule/abstractRule.js:33:21)
    at Rule.apply (/devel/src/hotfix/megaplan/front/node_modules/tslint-react/rules/jsxWrapMultilineRule.js:31:21)
    at Linter.applyRule (/usr/lib/node_modules/tslint/lib/linter.js:138:33)
    at Linter.lint (/usr/lib/node_modules/tslint/lib/linter.js:104:41)
    at TSLintPlugin.processLinting (/devel/bin/PhpStorm-171.3780.55/plugins/tslint/tslintLanguageService/tslint-plugin.js:76:20)
    at TSLintPlugin.getErrors (/devel/bin/PhpStorm-171.3780.55/plugins/tslint/tslintLanguageService/tslint-plugin.js:54:21)
    at TSLintPlugin.process (/devel/bin/PhpStorm-171.3780.55/plugins/tslint/tslintLanguageService/tslint-plugin.js:22:29)
```

**Comment by adidahiya** [comment]
Any chance you could provide a minimal code sample this fails with?

**Comment by Strate** [comment]
@adidahiya I think I could, but tomorrow :-)

**Comment by Strate** [comment]
N.B: running `tslint` command do not fail, fail only inside PhpStorm.

**Comment by IllusionMH** [comment]
@Strate is it possible that versions of TSLint on TypeScript used by phpStorm and CLI may differ?
Most commonly - local and global installation versions may be different.

**Comment by Strate** [comment]
@IllusionMH Ah, really, stackstrace contains path to `usr/lib/node_modules`, to global installation. I'll check it tomorrow and reopen this if something goes wrong.
